const AIRLINE_CODES = {
    // --- North America ---
    'AMERICAN AIRLINES': 'AA',
    'AMERICAN AIRLINES INC.': 'AA',
    'AMERICAN AIRLINES, INC.': 'AA',
    'AMERICAN': 'AA',
    'DELTA AIR LINES': 'DL',
    'DELTA': 'DL',
    'UNITED AIRLINES': 'UA',
    'UNITED': 'UA',
    'SOUTHWEST AIRLINES': 'WN',
    'SOUTHWEST': 'WN',
    'AIR CANADA': 'AC',
    'ALASKA AIRLINES': 'AS',
    'ALASKA': 'AS',
    'JETBLUE AIRWAYS': 'B6',
    'JETBLUE AIRWAYS CORPORATION': 'B6',
    'JETBLUE': 'B6',
    'SPIRIT AIRLINES': 'NK',
    'SPIRIT': 'NK',
    'FRONTIER AIRLINES': 'F9',
    'FRONTIER': 'F9',
    'HAWAIIAN AIRLINES': 'HA',
    'HAWAIIAN': 'HA',
    'WESTJET': 'WS',
    'WESTJET AIRLINES': 'WS',
    'AEROMEXICO': 'AM',
    'AEROMEXICO AIRLINES': 'AM',
    'AERO MEXICO': 'AM',
    'AERO MEXICO AIRLINES': 'AM',
    'VOLARIS': 'Y4',
    'INTERJET': '4O',
    'COPA AIRLINES': 'CM',
    'COPA': 'CM',
    'SUN COUNTRY AIRLINES': 'SY',
    'SUN COUNTRY': 'SY',
    'PORTER AIRLINES': 'PD',
    'PORTER': 'PD',

    // --- Regional North America ---
    'SKYWEST': 'OO',
    'REPUBLIC AIRWAYS': 'YX',
    'ENVOY AIR': 'MQ',
    'MESA AIRLINES': 'YV',
    'PSA AIRLINES': 'OH',
    'GOJET AIRLINES': 'G7',
    'HORIZON AIR': 'QX',
    'AIR WISCONSIN': 'ZW',

    // --- South America ---
    'LATAM AIRLINES': 'LA',
    'LATAM': 'LA',
    'AVIANCA': 'AV',
    'AVIANCA AIRLINES': 'AV',
    'AZUL BRAZILIAN AIRLINES': 'AD',
    'AZUL': 'AD',
    'GOL TRANSPORTES AEREOS': 'G3',
    'GOL': 'G3',
    'GOL LINHAS AEREAS': 'G3',
    'AEROLINEAS ARGENTINAS': 'AR',
    'AEROLINEAS': 'AR',

    // --- Europe ---
    'LUFTHANSA': 'LH',
    'BRITISH AIRWAYS': 'BA',
    'AIR FRANCE': 'AF',
    'AIRFRANCE': 'AF',
    'KLM ROYAL DUTCH AIRLINES': 'KL',
    'KLM': 'KL',
    'RYANAIR': 'FR',
    'RYAN AIR': 'FR',
    'EASYJET': 'U2',
    'EASY JET': 'U2',
    'EASYJET AIRLINE COMPANY': 'U2',
    'TURKISH AIRLINES': 'TK',
    'TURKISH': 'TK',
    'THY': 'TK',
    'TURK HAVA YOLLARI': 'TK',
    'IBERIA': 'IB',
    'IBERIA AIRLINES': 'IB',
    'SWISS INTERNATIONAL AIR LINES': 'LX',
    'SWISS': 'LX',
    'AER LINGUS': 'EI',
    'AERLINGUS': 'EI',
    'AEROFLOT': 'SU',
    'AEROFLOT RUSSIAN AIRLINES': 'SU',
    'AIR EUROPA': 'UX',
    'AIR EUROPA LINEAS AEREAS': 'UX',
    'ALITALIA': 'AZ',
    'ITA AIRWAYS': 'AZ',
    'ITA AIRWAYS S.P.A.': 'AZ',
    'ITA AIRWAYS SPA': 'AZ',
    'ITA': 'AZ',
    'AUSTRIAN AIRLINES': 'OS',
    'AUSTRIAN': 'OS',
    'BRUSSELS AIRLINES': 'SN',
    'FINNAIR': 'AY',
    'CONDOR': 'DE',
    'CONDOR AIRLINES': 'DE',
    'CONDOR FLUGDIENST': 'DE',
    'ICELANDAIR': 'FI',
    'ICELAND AIR': 'FI',
    'AIR TRANSAT': 'TS',
    'TRANSAT': 'TS',
    'EUROWINGS': 'EW',
    'EURO WINGS': 'EW',
    'LOT POLISH AIRLINES': 'LO',
    'LOT POLISH': 'LO',
    'LOT POLSKIE LINIE LOTNICZE': 'LO', // alias w/out dash
    'LOT – POLSKIE LINIE LOTNICZE': 'LO', // en dash variant observed on EU locales
    'LOT - POLSKIE LINIE LOTNICZE': 'LO',
    'NORWEGIAN AIR SHUTTLE': 'DY',
    'NORWEGIAN': 'DY',
    'NORWEGIAN AIR': 'DY',
    'SCANDINAVIAN AIRLINES': 'SK',
    'SAS': 'SK',
    'SCANDINAVIAN': 'SK',
    'TAP AIR PORTUGAL': 'TP',
    'TAP PORTUGAL': 'TP',
    'VIRGIN ATLANTIC': 'VS',
    'VIRGIN ATLANTIC AIRWAYS': 'VS',
    'VIRGIN ATLANTIC AIRLINES': 'VS',
    'VUELING': 'VY',
    'VUELING AIRLINES': 'VY',
    'WIZZ AIR': 'W6',
    'WIZZ': 'W6',
    'WIZZ AIR MALTA': 'W4',
    'PEGASUS AIRLINES': 'PC',
    'PEGASUS': 'PC',
    'PEGASUS HAVA YOLLARI': 'PC',
    'PEGASUS HAVA YOLLARI A S': 'PC',
    'PEGASUS HAVA YOLLARI A.S.': 'PC',
    'PEGASUS HAVA YOLLARI A.S': 'PC',
    'PEGASUS HAVA TASIMACILIGI A S': 'PC',
    'PEGASUS HAVA TASIMACILIGI A.S.': 'PC',
    'PEGASUS HAVA TASIMACILIGI A.S': 'PC',
    'PEGASUS HAVA TASIMACILIGI': 'PC',
    'PEGASUS HAVA TASIMACILIGI ANONIM SIRKETI': 'PC',
    'PEGASUS HAVA YOLLARI ANONIM SIRKETI': 'PC',
    'PEGASUS ASIA': 'PC',
    'PEGASUS ASIA AIRLINES': 'PC',
    'PEGASUS HAVAYOLLARI': 'PC',
    'PEGASUS HAVAYOLLARI A.S.': 'PC',
    'PEGASUS HAVAYOLLARI A.S': 'PC',
    'PEGASUS HAVAYOLLARI A S': 'PC',
    'PEGASUS HAVAYOLLARI ANONIM SIRKETI': 'PC',
    'PEGASUS AIRLINES AS': 'PC',
    'PEGASUS AIRLINES A.S.': 'PC',
    'TAROM': 'RO',
    'TAROM ROMANIAN AIR TRANSPORT': 'RO',
    'AEGEAN AIRLINES': 'A3',
    'AEGEAN AIR': 'A3',
    'AIR SERBIA': 'JU',
    'AIRSERBIA': 'JU',
    'AIR SERBIA A.D.': 'JU',
    'AIR SERBIA JSC': 'JU',
    'ANADOLUJET': 'TK',
    'ANADOLU JET': 'TK',
    'ANADOLUJET AIRLINES': 'TK',
    'AJET': 'TK',
    'A JET': 'TK',
    'HISKY': 'H4',
    'HI SKY': 'H4',
    'HISKY EUROPE': 'H4',
    'FLYONE': '5F',
    'FLY ONE': '5F',
    'AIR ASTANA': 'KC',
    'AIR ASTANA JSC': 'KC',
    'UZBEKISTAN AIRWAYS': 'HY',
    'UZBEKISTAN AIR': 'HY',
    'AZERBAIJAN AIRLINES': 'J2',
    'AZERBAIJAN AIRLINES (AZAL)': 'J2',
    'AZAL': 'J2',
    'GEORGIAN AIRWAYS': 'A9',
    'AIRZENA': 'A9',
    'TUI FLY': 'X3',
    'TUIFLY': 'X3',
    'TUI FLY DEUTSCHLAND': 'X3',
    'TUI FLY GERMANY': 'X3',

    // --- Asia & Oceania ---
    'SINGAPORE AIRLINES': 'SQ',
    'SINGAPORE AIR': 'SQ',
    'CATHAY PACIFIC': 'CX',
    'CATHAY PACIFIC AIRWAYS': 'CX',
    'CATHAY': 'CX',
    'ALL NIPPON AIRWAYS': 'NH',
    'ALL NIPPON': 'NH',
    'ANA': 'NH',
    'JAPAN AIRLINES': 'JL',
    'JAPAN AIR': 'JL',
    'JAL': 'JL',
    'QANTAS': 'QF',
    'QANTAS AIRWAYS': 'QF',
    'EMIRATES': 'EK',
    'EMIRATES AIRLINE': 'EK',
    'QATAR AIRWAYS': 'QR',
    'QATAR AIR': 'QR',
    'ETIHAD AIRWAYS': 'EY',
    'ETIHAD': 'EY',
    'KOREAN AIR': 'KE',
    'KOREAN': 'KE',
    'KOREAN AIRLINES': 'KE',
    'AIR CHINA': 'CA',
    'AIR CHINA LIMITED': 'CA',
    'CHINA SOUTHERN AIRLINES': 'CZ',
    'CHINA SOUTHERN': 'CZ',
    'CHINA EASTERN AIRLINES': 'MU',
    'CHINA EASTERN': 'MU',
    'HAINAN AIRLINES': 'HU',
    'HAINAN': 'HU',
    'EVA AIR': 'BR',
    'EVA AIRWAYS': 'BR',
    'EVA': 'BR',
    'THAI AIRWAYS': 'TG',
    'THAI': 'TG',
    'THAI AIR': 'TG',
    'MALAYSIA AIRLINES': 'MH',
    'MALAYSIA AIR': 'MH',
    'GARUDA INDONESIA': 'GA',
    'GARUDA': 'GA',
    'VIETNAM AIRLINES': 'VN',
    'VIETNAM AIR': 'VN',
    'PHILIPPINE AIRLINES': 'PR',
    'PHILIPPINES AIRLINES': 'PR',
    'AIR NEW ZEALAND': 'NZ',
    'AIR NEW ZEALAND LTD.': 'NZ',
    'VIRGIN AUSTRALIA': 'VA',
    'VIRGIN AUSTRALIA AIRLINES': 'VA',
    'ASIANA AIRLINES': 'OZ',
    'ASIANA': 'OZ',
    'AIR INDIA': 'AI',
    'AIR INDIA LIMITED': 'AI',
    'INDIGO': '6E',
    'INDIGO AIRLINES': '6E',
    'INDI GO': '6E',
    'SPICEJET': 'SG',
    'SPICE JET': 'SG',

    // --- Middle East & Africa ---
    'SAUDI ARABIAN AIRLINES': 'SV',
    'SAUDI ARABIAN': 'SV',
    'SAUDIA': 'SV',
    'EL AL': 'LY',
    'EL AL ISRAEL AIRLINES': 'LY',
    'ELAL': 'LY',
    'ROYAL JORDANIAN': 'RJ',
    'ROYAL JORDANIAN AIRLINES': 'RJ',
    'OMAN AIR': 'WY',
    'OMAN AIRWAYS': 'WY',
    'GULF AIR': 'GF',
    'GULF AIRLINES': 'GF',
    'EGYPTAIR': 'MS',
    'EGYPT AIR': 'MS',
    'EGYPTAIR AIRLINES': 'MS',
    'ETHIOPIAN AIRLINES': 'ET',
    'ETHIOPIAN': 'ET',
    'ETHIOPIAN AIR': 'ET',
    'KENYA AIRWAYS': 'KQ',
    'KENYA AIR': 'KQ',
    'SOUTH AFRICAN AIRWAYS': 'SA',
    'SOUTH AFRICAN AIR': 'SA',
    'SAA': 'SA',
    'ROYAL AIR MAROC': 'AT',
    'ROYAL AIR MAROC AIRLINES': 'AT',
    'RAM': 'AT'
};

// Normalized lookup helpers for airline aliases with punctuation/diacritics
function normalizeAirlineNameKey(name){
    if(!name && name !== 0) return '';
    let value = String(name);
    if(typeof value.normalize === 'function'){
        value = value.normalize('NFD').replace(/[\u0300-\u036f]/g, '');
    }
    value = value.toUpperCase().replace(/[^A-Z0-9]+/g, ' ').trim().replace(/\s+/g, ' ');
    return value;
}

const AIRLINE_NORMALIZED_CODES = {};
Object.keys(AIRLINE_CODES).forEach((key) => {
    const normalized = normalizeAirlineNameKey(key);
    if(normalized && !Object.prototype.hasOwnProperty.call(AIRLINE_NORMALIZED_CODES, normalized)){
        AIRLINE_NORMALIZED_CODES[normalized] = AIRLINE_CODES[key];
    }
});

function lookupAirlineCodeByName(name){
    if(!name && name !== 0) return null;
    const directKey = String(name).trim().toUpperCase();
    if(directKey && Object.prototype.hasOwnProperty.call(AIRLINE_CODES, directKey)){
        return AIRLINE_CODES[directKey];
    }
    const normalized = normalizeAirlineNameKey(name);
    if(normalized && Object.prototype.hasOwnProperty.call(AIRLINE_NORMALIZED_CODES, normalized)){
        return AIRLINE_NORMALIZED_CODES[normalized];
    }
    return null;
}

if(typeof window !== 'undefined'){
    window.lookupAirlineCodeByName = lookupAirlineCodeByName;
    window.normalizeAirlineNameKey = normalizeAirlineNameKey;
    window.AIRLINE_NORMALIZED_CODES = AIRLINE_NORMALIZED_CODES;
}
